
			<div class="row">
				<div class="col-md-12">
					<div class="widget">
						<header class="widget-header">
						<h4 class="widget-title">Editar usuarios</h4>
						</header>
						<hr class="widget-separator">
						<div class="widget-body">
							<div class="m-b-lg">
								<small>Formulario para añadir usuarios <?php echo $usuario["email"] ?></small>
							</div>
							<form class="form-horizontal" action="" method="POST" >
								<div class="form-group">
									<label for="exampleTextInput1" class="col-sm-3 control-label">Correo:</label>
									<div class="col-sm-9">
										<input class="form-control" name="email" placeholder="Your name" type="email" value="<?php echo $usuario["email"] ?>">
									</div>
								</div>
								<div class="form-group">
									<label for="email2" class="col-sm-3 control-label">Password:</label>
									<div class="col-sm-9">
										<input value="<?php echo $usuario["password"] ?>" class="form-control" name="password" placeholder="Password" type="password">
									</div>
								</div>
								<div class="form-group">
									<label for="email2" class="col-sm-3 control-label">Nombre:</label>
									<div class="col-sm-9">
										<input value="<?php echo $usuario["nombre"] ?>" class="form-control" name="nombre" placeholder="Nombre" type="text">
									</div>
								</div>
								<div class="form-group">
									<label for="email2" class="col-sm-3 control-label">Apellido:</label>
									<div class="col-sm-9">
										<input class="form-control" name="apellido" placeholder="Apellido" type="text">
									</div>
								</div>								
								<div class="row">
									<div class="col-sm-9 col-sm-offset-3">
										<button type="submit" class="btn btn-success">Comment</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>

			</div>


