

            <div class="row">
                <div class="col-md-12">
                <h4 class="m-b-lg">Listado de Usuarios <?php echo $var ?>
                        
                </div>
                    <div class="col-md-12">
                        <div class="widget p-lg">
                            <h4 class="m-b-lg">Detalle Usuario</h4>
                            <p class="m-b-lg docs">Vista detalle de usuario.</p>
                            <?php echo $usuario["email"]." - ".$usuario["nombre"]." - ".$usuario["apellido"]; ?>

                        </div>
                    </div>

                </div>
