<?php 
//Comprobamos si nos llega la sesión correcta o no, esto se puede hacer de distintas formas
if(!is_string($this->datos)){
$this->datos->id_user;
echo "Bienvenido ".$this->datos->usuario." ".$this->datos->id_personal."<br/>";
echo "Estas identificado con ".$this->datos->usuario;
?>
<p>
    <a class="btn btn-success" href="<?=$this->basePath("usuario/usuario/cerrar")?>">Cerrar sesión</a>
</p>   
<?php  
}else{
	
    echo $this->datos;
}
?>