<?php
//echo $_SERVER['SCRIPT_NAME'];
include_once("config/autoload/conexion.php");
$obcon= new Conexion("172.16.0.152","user_geresa","user_geresa2017","siganew",5432);
$consulta = "select * from remoto.view_personas";
$ejecquery = pg_query($obcon->getConexion(), $consulta);
?>
<div class="right_col" role="main">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<a class="btn btn-primary" href="<?php echo $this->basePath() ?>/personal/personal/form/0/1">Nuevo</a>
                    <ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
				</div>
				<div class="x_content">
					<h2>Lista de Personal</h2>
                    <table id="datatable" class="table table-striped table-bordered">
						<thead>
							<tr>
								<th style="width:30% " >Area</th>								
								<th style="width: 30% ">Personal</th>
								<th>DNI</th>
								<th>Responsable</th>
								<th> Vigencia </th>
								<th>Acciones</th>
								<th style="display:none">c</th>
							
							</tr>
						</thead>
						<tbody>
							
 <?php 
 while ($reg = pg_fetch_assoc($ejecquery)){
  echo "<tr>
    <td>".$reg['pers_id']."</td>
    <td>".$reg['pers_apellpaterno']."".$reg['pers_apellmaterno']."".$reg['pers_nombres']."</td>
		<td>".$reg['pers_dni']."</td>
   </tr>";
  }
 ?>

							<!--<?php foreach ($this->personals as $personal) { ?>
								<tr>
									<td><?php echo $personal['descripcion'] ?></td>
									<td><?php echo $personal['apellido_paterno'] ?>  <?php echo $personal['apellido_materno'] ?> <?php echo $personal['nombre'] ?> </td>
									<td><?php echo $personal['dni'] ?></td>
									<td><?= $personal['respatrimonial'] == true ? "<i class='fa fa-check'></i>" : "<i class='fa fa-remove'></i>"; ?></td>
									<td><?= $personal['vigencia'] == 1 ? "<i class='fa fa-check'></i>" : "<i class='fa fa-remove'></i>"; ?></td>
									<td>
										<a class="btn btn-default"href="<?php echo $this->basePath("personal/personal/form/1/" . $personal['id_personal'] . ""); ?>">Editar</a>
										<?= $personal['vigencia'] == 1 ? "<input type='button' class='btn btn-danger btnBorrar'  value='Eliminar'/>" : "<input type='button' class='btn btn-success btnActivar'  value='Activar'/>" ?>
									</td>
									<td id="idCod" style="display:none;"><?= $personal['id_personal'] ?></td>
								</tr>
							<?php } ?>-->
						</tbody>
						<tfoot>
							<tr>
								<th>Area</th>
								<th>Personal</th>
								<th>DNI</th>
								<th>Responsable</th>
								<th>Vigencia </th>
								<th>Acciones</th>
							</tr>
						</tfoot>
                    </table>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->basePath() ?>/vendors/jquery/dist/jquery.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/fastclick/lib/fastclick.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/nprogress/nprogress.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/jszip/dist/jszip.min.js"></script>
<script src="<?php echo $this->basePath() ?>/build/js/custom.min.js"></script>

<?=
		$this->inlineScript()
		->prependFile($this->basePath('js/js_personal.js'))
?>