<?php if ($mantenimiento != null) 
{ ?>
	<div class="right_col" role="main" style="min-height: 771px;">
	    <div class="">
	        <div class="clearfix"></div>
	        <div class="row">
	            <div c="" lass="col-md-12 col-sm-12 col-xs-12">
	                <div class="x_panel">
	                    <div class="x_title">
	                        <h2><?php echo $this->mantenimiento ?> Tipo de Acción </h2>
	                        <ul class="nav navbar-right panel_toolbox">
	                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
	                        </ul>
	                        <div class="clearfix"></div>
	                    </div>

	                    <div class="x_content">
	                    <br>

	                        <div class="form-group">

								<label class="col-sm-1 control-label"><b>Tipo:</b></label>

								<div class="col-sm-2">

									<input type="hidden" class="" name="txtId" id="txtId"  placeholder="" value="<?= $datos != null ? $datos['id_accion'] : ''; ?>">
					
									
										<select class="form-control" name="cmbTipo" id="cmbTipo">
										<?php 
											if($this->datos == null)
											{
										?>
												<option  value='' > Seleccione...</option>
												<option value='H' > Hardware</option>
												<option value='S' > Software</option>
										<?php
											}
											else
											{
												if($datos['tipo']=='H')
												{
												?>
													<option selected value='H'>Hardware</option>
													<option  value='S' > Software</option>
												<?php 
												}
												else
												{
												?>
													<option value='H' > Hardware</option>
													<option selected value='S'>Software</option>
										<?php 
												}
											}
										?>



										</select>
	
								</div>
								<label class="col-sm-1 control-label"><b>Descripción:</b></label>
								<div class="col-sm-4">
									<input type="hidden" class="" name="txtId" id="txtId"  placeholder=""  value="<?= $datos != null ? $datos['id_accion'] : ''; ?>">
	                                <input type="text" id="txtDescripcion" name="txtDescripcion" class="form-control" value="<?= $datos != null ? $datos['descripcion'] : ''; ?>">

								</div>
	                        </div>



						</div>
						<hr>
						<div class="form-group">
							<center>
								<div class="col-sm-9">
									<button type="submit" id="btnguardar" class="btn btn-primary">
										<?php echo $this->textBoton ?>
									</button>
								</div>
							</center>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
	</div>

<?php } ?>
<script src="<?php echo $this->basePath() ?>/vendors/jquery/dist/jquery.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/fastclick/lib/fastclick.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/nprogress/nprogress.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/moment/min/moment.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
<script src="<?php echo $this->basePath() ?>/build/js/custom.min.js"></script>


<?=
		$this->inlineScript()
		->prependFile($this->basePath('js/js_accion.js'))
?>