<?php if ($mantenimiento != null) { ?>
	<style>
		.progressBar { position:relative; width:400px; border: 1px solid #ddd; padding: 1px; border-radius: 3px; }
		.bar { background-color: #B4F5B4; width:0%; height:20px; border-radius: 3px; }
		.percent { position:absolute; display:inline-block; top:-43px; left:48%; }
	</style>
<div class="right_col" role="main">
		<div class="">
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="x_panel">
						<div class="x_title">
							<h2><strong><?php echo $this->mantenimiento;?> Ficha Tecnica de Equipos</strong><small></small></h2>
							<ul class="nav navbar-right panel_toolbox">
								<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
							</ul>
							<div class="clearfix"></div>
						</div>
						<input type="hidden" id="txtIdficha" value="<?=$datosFicha['id_ficha_tecnica']?>">
						<div class="x_content">
							<h2 class="StepTitle"><strong>Datos Generales</strong></h2>
							<form class="form-horizontal form-label-left">
								<div class="form-group" >
									<label class="col-sm-2 control-label"><b>Equipo:</b></label>
									<div class="col-sm-4">
										<input class="form-control " name="txtIdEquipo" id="txtIdEquipo" value="<?=$datosFicha['id_disp_soft']?>" type="hidden" >
										<input class="form-control  ui-autocomplete-input" name="txtEquipo" id="txtEquipo" value="<?=$datosFicha['dispositivo']?>" value=""style="text-transform:uppercase" placeholder="Buscar..." type="text" autocomplete="off">
									</div>
									<label class="col-sm-2 control-label"><b>Nº Ficha:</b></label>
									<div class="col-sm-4">
										<input class="form-control "  align=\"right\"  id="txtNroFicha" name="txtNroFicha"  value="<?=$datosFicha['numero']?>" type="hidden" >
										<label align=\"right\" ><?=$datosFicha['numero']?></label>
										<input class="form-control "  align=\"right\"  id="txtIdNroUniOrg" name="txtIdNroUniOrg"  value="<?= $this->uni_org?>" type="hidden" >
									</div>
								</div>
								<div id="divDatosNuevo" >
								<div class="form-group" >
									
									<label class="col-sm-2 control-label"><b>Fecha_Inv:</b></label>
									<div class="col-sm-4">
									<?php
										$fechaInv=explode("-",$datosFechaInv['fecha_inventario']);
									?>
										<input type='date' class="form" id="txtFecha" name="txtFecha" value='<?= ( $fechaInv[0] . "-" . $fechaInv[1] . "-" .$fechaInv[2])?>'>
									</div>
									<label class="col-sm-2 control-label"><b>Fecha_Inst:</b></label>
									<div class="col-sm-4">
									<?php
										$fechaIns=explode("-",$datosFicha['fecha_instalacion']);
									?>
										<input type='date' class="form" id="txtFechaInstalacion" name="txtFechaInstalacion" value='<?= ($fechaIns[0] . "-" . $fechaIns[1] . "-" . $fechaIns[2]); ?>'>
									</div>
									
									<!--div class="col-sm-1">
										<input class="form-control "  id="txtAnioNroFicha"  name="txtAnioNroFicha" value="<?= date("Y"); ?>" type="text" >
									</div-->
								</div>
								<div class="form-group" >
									<label class="col-sm-2 control-label"><b>Unidad Organica:</b></label>
									<div class="col-sm-4">
										<input class="form-control "  id="txtIdUnidadOrganica"  name="txtIdUnidadOrganica" type="hidden" value="<?=$datosRespArea['id_uni_org']?>" >
										<input type="text" id="txtUnidadOrganica" name="txtUnidadOrganica"  disabled  class="form-control" style="text-transform:uppercase"  value="">
									</div>
									<label class="col-sm-2 control-label"><b>Area/Servicio:</b></label>
									<div class="col-sm-4">
										<input class="form-control "  id="txtIdAreaServ"  name="txtIdAreaServ" type="hidden" value="<?=$datosRespArea['id_area']?>" >
										<input class="form-control "  id="txtAreaServ" name="txtAreaServ" type="text" value="<?=$datosRespArea['area']?>"  disabled  style="text-transform:uppercase">
									</div>
								</div>
								<div class="form-group" >
									<label class="col-sm-2 control-label"><b>Responsable Patrimonio:</b></label>
									<div class="col-sm-4">
										<input class="form-control "  id="txtIdRespPatrimonio" name="txtIdRespPatrimonio" placeholder="BUSCAR"value="<?=$datosRespArea['id_reppatrimonio']?>"  type="hidden" style="text-transform:uppercase" >
										<input class="form-control "  id="txtRespPatrimonio" name="txtRespPatrimonio" disabled value="<?php $res=explode("\\",$datosRespArea['respatrimonial']);echo $res[1]?>" type="text" style="text-transform:uppercase" >
									</div>
									<label class="col-sm-2 control-label"><b>Responsable Funcion:</b></label>
									<div class="col-sm-4">
										<input class="form-control "  id="txtIdRespFuncionario" name="txtIdRespFuncionario" placeholder="BUSCAR" value="<?=$datosRespArea['id_respfuncionario']?>" type="hidden" style="text-transform:uppercase"	>
										<input class="form-control "  id="txtRespFuncionario" name="txtRespFuncionario"  placeholder="BUSCAR" value="<?=$datosRespArea['funcionario']?>" type="text" style="text-transform:uppercase"	>
									</div>
								</div>
								<div class="form-group" >
									<label class="col-sm-2 control-label"><b>Observación:</b></label>
									<div class="col-sm-10">
										<input class="form-control " name="txtObservacion" id="txtObservacion" value="<?=$datosFicha['observacion']?>" type="text" >
										
									</div>
								</div>
								<div class="form-group" >
									<a class="btn btn-alert" id="btnAnadirEditDAd" class="col-sm-4"> <i class="fa fa-plus" aria-hidden="true"></i> Ver Datos de Adquisicion</a>
								</div>
									</div>
							</form><br/><hr/>
						</div>
					</div>
					<div id="datosAdquisicion" class="x_panel" style="display:none" >
						<div class="x_title">
							
							<h2><strong>DATOS DE ADQUISICIÓN</strong><small></small></h2>
							<ul class="nav navbar-right panel_toolbox">
								<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
							</ul>
							<div class="clearfix"></div>
						</div>
						<input type="hidden" id="ficha" value="0">
						<div class="x_content" >
							<form class="form-horizontal form-label-left">
								<div class="form-group" >
									<label class="col-sm-1 control-label"><b>Documento:</b></label>
									<div class="col-sm-3">
										<select id="cmbDocumento" class="form-control"name="cmbDocumento">
												<?php foreach ($this->docAdquisicion  as $datosAdquisicion) { ?>
											<option value="<?php echo $datosAdquisicion['id_doc_adquisicion'] ?>"><?php echo $datosAdquisicion['abreviatura'] ?> - <?php echo $datosAdquisicion['descripcion'] ?></option>
												<?php } ?>
										</select>
									</div>
									<label class="col-sm-1 control-label"><b>Nº DOC.</b></label>
									<div class="col-sm-3">
										<input class="form-control "  id="txtDocumento" name="txtDocumento" placeholder="Numero"  value="" type="text" >
									</div>
										<label class="col-sm-1 control-label"><b>Fecha:</b></label>
												<div class="col-sm-2">
													<input class="form-control"  id="txtFechaDoc" name="txtFechaDoc" value='<?= (date("Y") . "-" . date("m") . "-" . date("d")); ?>' type="date">
												</div>
									<div class="col-sm-1">
											<button class="btn btn-success " id="btnAnadirDocumento"> <i class="fa fa-plus" aria-hidden="true"></i> Añadir</button>
										</div>
								</div>
								
								<div class="form-group">
										<div class="col-md-12">
											
											<table id="tabla_adquisicion"  class="table table-striped table-bordered">
												<thead>
													<tr style="background: #e1e4e8">
														<th width="5%">#</th>
														<th hidden></th>
														<th width="30%">Documento</th>
														<th hidden></th>
														<th width="25%">Numero</th>
														<th width="25%">Fecha</th>
														<th width="25%">Adjunto</th>
														<th width="25%">Vigencia</th>
														<th width="30%">Accion</th>
													</tr>
												</thead>
												<tbody id="datosBDAd" name="datosBDAd">
													
												</tbody>
											</table>
											
											<table id="tabla_adquisicion"  class="table table-striped table-bordered">
												<!--<thead>
													<tr style="background: #e1e4e8">
														<th width="5%">#</th>
														<th hidden></th>
														<th width="30%">Documento</th>
														<th hidden></th>
														<th width="25%">Numero</th>
														<th width="25%">Fecha</th>
														<th width="30%">Accion</th>
													</tr>
												</thead>-->
												<tbody>
												</tbody>
											</table>			
										</div>
								</div>
							</form>
							<form  class="form-horizontal form-label-left" action="../../subirArchivo" id="frmSubir" name="frmSubir" method="post" enctype="multipart/form-data">
								<br/>
								<label class="col-sm-1 control-label">Archivo</label>	
								<div class="col-sm-4">
									
									 <input type="hidden" name="MAX_FILE_SIZE" value="1000000000000000000" />
        <input name="uploadedfile" id="uploadedfile" type="file" />
    <br />
								</div>
								<div class="col-sm-2"><input type="submit" value="Subir"></div>
								<div class="col-sm-5">
									<div class="progressBar">
										<div class="bar"></div >
										<div class="percent">0</div >
									</div>
								</div>
							</form>
							<br/><hr/>
						</div>
					</div>
					<div class="x_panel">
						<div class="x_title">
							<h2><strong>DETALLE FICHA TÉCNICA</strong><small></small></h2>
									<a class="btn btn-alert" id="btnAnadirDetaFicha" class="col-sm-4"> <i class="fa fa-plus" aria-hidden="true"></i> Ver Detalle</a>
							<ul class="nav navbar-right panel_toolbox">
								<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
							</ul>
							<div class="clearfix"></div>
						</div>

						<div class="x_content">
							<div id="divComponentes" style="display:none">

								<div class="form-horizontal form-label-left">
									<div class="form-group">
										<input type="hidden" id="txtFichaIdDis">	
										<input type="hidden" id="disp">
										<input type="hidden" id="mar">
										<label class="col-sm-2 control-label"><b>Marca / Modelo:</b></label>
										<div class="col-sm-4">
											<input type="text" id="txtFichaMaMo" name="txtFichaMaMo" class="form-control" placeholder="Buscar" value="" style="text-transform:uppercase">
										</div>
										<label for="" class="col-sm-2 control-label"><b>Serie:</b></label>
										<div class="col-sm-3">
											<input class="form-control" name="txtFichaSerieMaMo" id="txtFichaSerieMaMo" type="text" value="" style="text-transform:uppercase">
											<input type="hidden" id="txtIdDisMaMo">
										</div>
										<div class="col-sm-1">
											<label id='lblNSerieMaMo2' style="color:red; display: none" > <img src="../../../../img/uncheck.png" width="20px" height="20px" >Ya Existe!</label>
											<label  id='lblASerieMaMo2'style='display: none'> <img src="../../../../img/check.png" width="20px" height="20px" ></label>
										</div>
									</div>
									<div class="form-group">
										<label for="" class="col-sm-2 control-label"><b>Cod. Inventario:</b></label>
										<div class="col-sm-4">
											<input class="form-control" name="txtFichaCodInventario" id="txtFichaCodInventario" type="text" value="" style="text-transform:uppercase">
											<input type="hidden" id="txtIdDisMaMo">
										</div>
										<label class="col-sm-2 control-label" for="chkOpFichaDisp" ><b>Operativo:</b></label>
										<div class="col-sm-1">
											<?=
											$datos != null ? $datos['vigencia'] == true ?
															'<input type="checkbox" name="chkOpFichaDisp" id="chkOpFichaDisp" value="1" checked>' :
															'<input type="checkbox" name="chkOpFichaDisp" id="chkOpFichaDisp" value="1">' :
													'<input type="checkbox" name="chkOpFichaDisp" id="chkOpFichaDisp" value="1"  checked><br>';
											?>
										</div>
										
									</div>
									<div class="form-group" id="divTelefono" style="display:none" >
										<div id="IMEI" style="display:none">
										<label class="col-sm-2 control-label"><b>IMEI:</b></label>
										<div class="col-sm-4">
											<input type="text" id="txtIMEI" name="txtIMEI" class="form-control"  value="" style="text-transform:uppercase">
										</div>
										</div>
										<div id="FECHAAD" style="display:none">										
											<label for="" class="col-sm-2 control-label"><b>Fecha de adquisición:</b></label>
										<div class="col-sm-3">
											<input class="form-control" name="txtFACel" id="txtFACel" type="date" value="">
										</div>
										</div>
									</div>
									<div class="form-group">
										<div id="FECHAREN" style="display:none">
										<label class="col-sm-2 control-label"><b>Fecha de renovación:</b></label>
										<div class="col-sm-3">
											<input class="form-control" name="txtFRCel" id="txtFRCel" type="date" value="">
										</div>
										</div>
										<label for="" class="col-sm-2 control-label"><b></b></label>
										<div class="col-sm-3">
											<button  class="btn btn-success " id="btnAnadirFichaDisp"> <i class="fa fa-plus" aria-hidden="true"></i> Añadir</button>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<table id="tabla_ficha_disp" class="table table-striped table-bordered">
												<thead>
													<tr>
														<th width="5%">#</th>
														<th hidden></th>
														<th width="30%">Marca - Modelo</th>
														<th width="25%">Serie</th>
														<th width="25%">Inventario</th>
														<th width="25%" id="tblIMEI" name="tblIMEI" style="display:none" >IMEI</th>
														<th width="25%" id="tblFAdquisicion" name="tblFAdquisicion" style="display:none">F.Adquisición</th>
														<th width="25%" id="tblFRenovacion" name="tblFRenovacion" style="display:none">F.Renovación</th>
														<th width="8%">Operativo</th>
														<th width="30%">Accion</th>
													</tr>
												</thead>
												<tbody>
												</tbody>
											</table>			
										</div>
										<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><center><button class="btn btn-primary " id="btnguardar"> <i class="fa fa-plus" aria-hidden="true"></i> Registrar FICHA</button></center>
									</div>
								</div>
							</div>
							<div id="wizard" class="form_wizard wizard_horizontal" id="tab" >
								<ul class="wizard_steps" style="display: none" >
									<li>
										<a href="#step-1" id="tab1">
											<span class="step_no">1</span>
											<span class="step_descr">Paso 1<br />
												<small>Datos Espeficos</small>
											</span>
										</a>
									</li>
									<li>
										<a href="#step-2" id="tab2">
											<span class="step_no">2</span>
											<span class="step_descr">Paso 2<br />
												<small>Componentes Internos</small>
											</span>
										</a>
									</li>
									<li>
										<a href="#step-3" id="tab3">
											<span class="step_no">3</span>
											<span class="step_descr">Paso 3<br />
												<small>Otros Componentes</small>
											</span>
										</a>
									</li>
									<li>
										<a href="#step-4" id="tab4">
											<span class="step_no">4</span>
											<span class="step_descr">Paso 4<br />
												<small>Software</small>
											</span>
										</a>
									</li>
								</ul>
								<hr>
								<div id="step-1"style="display: none"  >
									<div id="stepEspecifico" >
										<h2 class="StepTitle"><strong>Datos Especificos</strong></h2>
										<form class="form-horizontal form-label-left">
											<div class="form-group">
												<div id="pcCompatible">
													<label class="col-sm-2 control-label" for="chkCompatible" ><b>Compatible:</b></label>
													<div class="col-sm-1">
														<?=
														$datosEspecifico!= null ? $datosEspecifico['compatible'] == true ?
																		'<input type="checkbox" name="chkCompatible" id="chkCompatible" value="1" checked>' :
																		'<input type="checkbox" name="chkCompatible" id="chkCompatible" value="1">' :
																'<input type="checkbox" name="chkCompatible" id="chkCompatible" value="1"><br>';
														?>
													</div>

												</div>
												<label class="col-sm-1 control-label" for="chkOpOtros" ><b>Operativo:</b></label>
												<div class="col-sm-1">
													<?=
													$datosEspecifico != null ? $datosEspecifico['operativo'] == true ?
																	'<input type="checkbox" name="chkOpOtros" id="chkOpOtros" value="1" checked>' :
																	'<input type="checkbox" name="chkOpOtros" id="chkOpOtros" value="1">' :
															'<input type="checkbox" name="chkOpOtros" id="chkOpOtros" value="1"  checked><br>';
													?>
												</div>
												<label class="col-sm-2 control-label" for="chkGarantia" ><b>Garantia:</b></label>
												<div class="col-sm-1">
													<?=
													$datosEspecifico != null ?
															$datosEspecifico['garantia'] == true ?
																	'<input type="checkbox" name="chkGarantia" id="chkGarantia" value="1" checked>' : '<input type="checkbox" name="chkGarantia" id="chkGarantia" value="1">' :
															'<input type="checkbox" name="chkGarantia" id="chkGarantia" value="1" ><br>';
													?>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-2 control-label"><b>Nombre de PC:</b></label>
												<div class="col-sm-3">
													<input class="form-control "  id="txtNomPc" name="txtNomPc" type="text"  value="<?=$datosFicha['nompc']?>" style="text-transform:uppercase" >
												</div>
												<label class="col-sm-2 control-label"><b>F. Adquisicion:</b></label>
												<div class="col-sm-2">
													<input class="form-control"  id="txtFechaAdquisicion" name="txtFechaAdquisicion" value='<?= (date("Y") . "-" . date("m") . "-" . date("d")); ?>' type="date">
												</div>
												<div id="divAnioGarantia" style="display:none">
													<label class="col-sm-1 control-label" ><b>Garantia:</b></label>
													<div class="col-sm-1">
														<input type="text" id="txtAnioGarantia" name="txtAnioGarantia" placeholder="años"  class="form-control"  value="<?= $datosEspecifico != null ? $datosEspecifico ['anio_garantia'] : ''; ?>">
													</div>
												</div>
											</div>
											<div class="form-group" id="datosPC">
												<label class="col-sm-2 control-label"><b>Marca:</b></label>
												<div class="col-sm-3">
													<input type="hidden" class="" name="txtIdMPc" id="txtIdMPc"  placeholder=""  value="<?= $datosEspecifico!= null ? $datosEspecifico['id_marca'] : ''; ?>">
													<input class="form-control " name="txtMarcaPC" id="txtMarcaPC" placeholder="Buscar..." value="<?=$datosEspecifico['marca']?>" type="text" style="text-transform:uppercase">
												</div>
												<label class="col-sm-2 control-label"><b>Serie:</b></label>
												<div class="col-sm-3">
													<input class="form-control "  id="txtSeriePC" name="txtSeriePC" type="text" value="<?=$datosEspecifico['serie']?>" style="text-transform:uppercase">
												</div>
												<div class="col-sm-1">
													<label id='lblNSeriePc' style="color:red; display: none" > <img src="../../../../img/uncheck.png" width="20px" height="20px" >Ya Existe!</label>
													<label  id='lblASeriePc'style='display: none'> <img src="../../../../img/check.png" width="20px" height="20px" ></label>
												</div>
											</div>
											<div class="form-group" >
												<label class="col-sm-2 control-label"><b>N° Patrimonial:</b></label>
												<div class="col-sm-3">
													<input type="text" name="txtNroPatrimonio" id="txtNroPatrimonio" value="" class="form-control col-md-6 col-xs-10" style="text-transform:uppercase">
												</div>
												<div class="col-sm-2"></div>
											</div>
											<!--h2 class="StepTitle"><strong>S.O.</strong></h2><br/>
											<div class="form-group">
												<label class="col-sm-2 control-label"><b>Sistema Operativo:</b></label>
												<div class="col-sm-3">
													<input type="hidden" class="" name="txtIdSO" id="txtIdSO"  placeholder=""  value="<?= $datos != null ? $datos['id_disp_soft'] : ''; ?>">
													<input class="form-control " name="txtSO" id="txtSO" placeholder="Buscar..." value="" type="text" style="text-transform:uppercase">
												</div>
												<label class="col-sm-2 control-label"><b>Nro Licencia:</b></label>
												<div class="col-sm-3">
													<input type="text" id="txtLicenciaSO" name="txtLicenciaSO" class="form-control" value="" style="text-transform:uppercase">
												</div>
												<div class="col-sm-1">
													<label id='lblNLicenciaSO' style="color:red; display: none" > <img src="../../../../img/uncheck.png" width="20px" height="20px" >Ya Existe!</label>
													<label  id='lblALicenciaSO'style='display: none'> <img src="../../../../img/check.png" width="20px" height="20px" ></label>
												</div>

											</div-->
											<hr/>
											<h2 class="StepTitle"><strong>Cuentas</strong></h2><br/>
											<div class="form-group">
												<label class="col-sm-1 control-label"><b>Tipo:</b></label>
												<div class="col-sm-2">
													<select class="form-control" id="cmbTipoUser" name="cmbTipoUser">
														<option value="U">Usuario</option>
														<option value="A">Administrador</option>
													</select>
												</div>
												<label class="col-sm-1 control-label"><b>Usuario:</b></label>
												<div class="col-sm-2">
													<input type="hidden" class="" name="txtIdUsuario" id="txtIdUsuario"  value="">
													<input class="form-control " name="txtUsuario" id="txtUsuario" value="" type="text" style="text-transform:uppercase">
												</div>
												<label class="col-sm-1 control-label"><b>Contraseña:</b></label>
												<div class="col-sm-2">
													<input type="password" id="txtPass" name="txtPass" value="" class="form-control" style="text-transform:uppercase">
												</div>
												<div class="col-sm-2">
													<button class="btn btn-success " id="btnAnadirUser"> <i class="fa fa-plus" aria-hidden="true"></i> Añadir</button>
												</div>
											</div>
											<div class="form-group">
												<div class="col-md-12">
													<table id="tabla_user" class="table table-striped table-bordered">
														<thead>
															<tr>
																<th width="5%">#</th>
																<th hidden></th>
																<th width="20%">Tipo</th>
																<th hidden></th>
																<th width="25%">Usuario</th>
																<th width="25%">Contraseña</th>
																<th width="30%">Accion</th>
															</tr>
														</thead>
														<tbody>
														</tbody>
													</table>			
												</div>
												<br/><br/><br/>
												<br/><br/><br/>
											</div>
										</form>
										<br/>
										<br/>
									</div>
								</div>
								<div id="step-2" style="display: none" >
									<h2 class="StepTitle"><strong>Componentes Internos</strong></h2><br/>
									<form class="form-horizontal form-label-left">
										<div class="form-group">
											<label class="col-sm-2 control-label"><b>Microprocesador:</b></label>
											<div class="col-sm-4">
												<input type="hidden" class="" name="txtIdMI" id="txtIdMI"  placeholder=""  value="<?= $datos != null ? $datos['id_disp_soft'] : ''; ?>">
												<input class="form-control " name="txtMI" id="txtMI" placeholder="Buscar..." type="text" value="" style="text-transform:uppercase">
											</div>
											<label class="col-sm-2 control-label"><b>Estruct(Bits)</b></label>
											<div class="col-sm-2">
												<input type="radio" name="rbBits" id="rbBits" value="32" checked>x32 <input type="radio" name="rbBits" id="rbBits" value="64" >x64
											</div>
										</div>

										<div class="form-group">
											<label class="col-sm-2 control-label"><b>Disco Duro:</b></label>
											<div class="col-sm-4">
												<input type="hidden" class="" name="txtIdDD"  id="txtIdDD"   placeholder=""  value="<?= $datos != null ? $datos['id_disp_soft'] : ''; ?>"  >
												<input class="form-control " name="txtDD" id="txtDD" style="text-transform:uppercase" value="" placeholder="Buscar..." type="text">
											</div>
											<label class="col-sm-2 control-label"><b>Serie:</b></label>
											<div class="col-sm-3">
												<input type="text" id="txtSerieDD" name="txtSerieDD" class="form-control" value="" style="text-transform:uppercase">
											</div>
											<div class="col-sm-1">
												<label id='lblNSerieDD' style="color:red; display: none" > <img src="../../../../img/uncheck.png" width="20px" height="20px" >Ya Existe!</label>
												<label  id='lblASerieDD'style='display: none'> <img src="../../../../img/check.png" width="20px" height="20px" ></label>
											</div>
										</div>
										<div class="form-group">
											<label class="col-sm-2 control-label"><b>Mainboard:</b></label>
											<div class="col-sm-4">
												<input type="hidden" class="" name="txtIdMain" id="txtIdMain"  placeholder=""  value="<?= $datos != null ? $datos['id_disp_soft'] : ''; ?>">
												<input class="form-control " name="txtMain" id="txtMain" placeholder="Buscar..." value="" type="text" style="text-transform:uppercase">
											</div>
											<label class="col-sm-2 control-label"><b>Serie:</b></label>
											<div class="col-sm-3">
												<input type="text" id="txtSerieMain" name="txtSerieMain" class="form-control" value="" style="text-transform:uppercase">
											</div>
											<div class="col-sm-1">
												<label id='lblNSerieMain' style="color:red; display: none" > <img src="../../../../img/uncheck.png" width="20px" height="20px" >Ya Existe!</label>
												<label  id='lblASerieMain'style='display: none'> <img src="../../../../img/check.png" width="20px" height="20px" ></label>
											</div>
										</div>
										<hr>
										<h2 class="StepTitle"><strong>RAM</strong></h2><br/>
										<div class="form-group">
											<label class="col-sm-1 control-label"><b>Memoria:</b></label>
											<div class="col-sm-4">
												<input type="hidden" class="" name="txtIdMR" id="txtIdMR"  placeholder=""  value="<?= $datos != null ? $datos['id_disp_soft'] : ''; ?>">
												<input class="form-control " name="txtMR" id="txtMR" placeholder="Buscar..." type="text" value="" style="text-transform:uppercase">
											</div>
											<div class="col-sm-2">
												<button class="btn btn-success " id="btnAnadirRam"> <i class="fa fa-plus" aria-hidden="true"></i> Añadir</button>
											</div>
											<div class="col-md-5">
												<table id="tabla_ram" class="table table-striped table-bordered">
													<thead>
														<tr>
															<th width="5%">#</th>
															<th hidden></th>
															<th width="40%">Dispositivo</th>
															<th width="10%">Accion</th>
														</tr>
													</thead>
													<tbody>
													</tbody>
												</table>			
											</div>
										</div>
										<hr/>
										<h2 class="StepTitle"><strong>RED</strong></h2><br/>
										<div class="form-group">
											<label class="col-sm-1 control-label" for="chkRedIntegrada" ><b>Integrada:</b></label>
											<div class="col-sm-1">
												<?=
												$datos != null ? $datos['inetgrada'] == true ?
																'<input type="checkbox" name="chkRedIntegrada" id="chkRedIntegrada" value="1" checked>' :
																'<input type="checkbox" name="chkRedIntegrada" id="chkRedIntegrada" value="1">' :
														'<input type="checkbox" name="chkRedIntegrada" id="chkRedIntegrada" value="1"  ><br>';
												?>
											</div>

											<label class="col-sm-1 control-label" for="chkConRed" ><b>En Red:</b></label>
											<div class="col-sm-1">
												<?=
												$datos != null ? $datos['enred'] == true ?
																'<input type="checkbox" name="chkConRed" id="chkConRed" value="1" checked>' :
																'<input type="checkbox" name="chkConRed" id="chkConRed" value="1">' :
														'<input type="checkbox" name="chkConRed" id="chkConRed" value="1" checked  ><br>';
												?>
											</div>
											<label class="col-sm-1 control-label" for="chkConInternet" ><b>Internet:</b></label>
											<div class="col-sm-1">
												<?=
												$datos != null ? $datos['internet'] == true ?
																'<input type="checkbox" name="chkConInternet" id="chkConInternet" value="1" checked>' :
																'<input type="checkbox" name="chkConInternet" id="chkConInternet" value="1">' :
														'<input type="checkbox" name="chkConInternet" id="chkConInternet" value="1" checked  ><br>';
												?>
											</div>
										</div>	
										<div class="form-group">
											<div id="integrada">
												<label class="col-sm-1 control-label"><b>Tarjeta:</b></label>
												<div class="col-sm-3">
													<input type="hidden" class="" name="txtIdRed" id="txtIdRed"  placeholder=""  value="<?= $datos != null ? $datos['id_disp_soft'] : ''; ?>">
													<input class="form-control " name="txtRed" id="txtRed" placeholder="Buscar..." type="text" value="" style="text-transform:uppercase">
												</div>
												<label class="col-sm-1 control-label"><b>Serie:</b></label>
												<div class="col-sm-3">
													<input type="text" id="txtSerieRed" name="txtSerieRed" class="form-control" value="" style="text-transform:uppercase">
												</div>
											</div>
											<div class="col-sm-1">
												<label id='lblNSerieRed' style="color:red; display: none" > <img src="../../../../img/uncheck.png" width="20px" height="20px" >Ya Existe!</label>
												<label  id='lblASerieRed'style='display: none'> <img src="../../../../img/check.png" width="20px" height="20px" ></label>
											</div>
											<label class="col-sm-1 control-label"><b>MAC:</b></label>
											<div class="col-sm-3">
												<input type="text" id="txtMac" name="txtMac" placeholder="0A-0B-0C-AD-D0-D0" class="form-control" value="" style="text-transform:uppercase">
											</div>
										</div>
										<div class="form-group">
											<label class="col-sm-1 control-label"><b>IP v4/v6:</b></label>
											<div class="col-sm-2">
												<input type="hidden" class="" name="txtIdIPAdd" id="txtIdIPAdd"  placeholder=""  value="<?= $datos != null ? $datos['id_disp_soft'] : ''; ?>">
												<input class="form-control " name="txtIPAdd" id="txtIPAdd" placeholder="Buscar..." type="text"  value="" style="text-transform:uppercase">
											</div>
											<div class="col-sm-1"></div>
											<label class="col-sm-2 control-label"><b>Puerta Enlace:</b></label>
											<div class="col-sm-2">
												<input class="form-control" name="txtPuertaEnlance" id="txtPuertaEnlance" type="text" value="" style="text-transform:uppercase">
											</div>
											<div class="col-sm-1"></div>
											<label class="col-sm-2 control-label"><b>Proxy:</b></label>
											<div class="col-sm-2">
												<input class="form-control" name="txtProxy" id="txtProxy" type="text" value="" style="text-transform:uppercase">
											</div>

										</div>
									</form>
									<br>
								</div>
								<div id="step-3" style="display:none">
									<h2 class="StepTitle"><strong>Otros Componentes</strong></h2>
									<div class="form-horizontal form-label-left">
										<div class="form-group">
											<label for="" class="col-sm-1 control-label"><b>Disp:</b></label>
											<div class="col-sm-4">
												<input class="form-control" name="txtDispositivo" id="txtDispositivo" type="text" placeholder="Buscar" value="" style="text-transform:uppercase">	
												<input type="hidden" id="txtIdDis">	
												<input type="hidden" id="disp">
												<input type="hidden" id="mar">

											</div>
											<label class="col-sm-2 control-label"><b>Marca / Modelo:</b></label>
											<div class="col-sm-4">

												<input type="text" id="txtMaMo" name="txtMaMo" class="form-control" placeholder="Buscar" value="" style="text-transform:uppercase">
											</div>
										</div>
										<div class="form-group">
											<label for="" class="col-sm-1 control-label"><b>Serie:</b></label>
											<div class="col-sm-4">
												<input class="form-control" name="txtSerieMaMo" id="txtSerieMaMo" type="text" value="" style="text-transform:uppercase">
												<input type="hidden" id="txtIdDisMaMo">
											</div>
											<div class="col-sm-1">
												<label id='lblNSerieMaMo' style="color:red; display: none" > <img src="../../../../img/uncheck.png" width="20px" height="20px" >Ya Existe!</label>
												<label  id='lblASerieMaMo'style='display: none'> <img src="../../../../img/check.png" width="20px" height="20px" ></label>
											</div>
											<div class="col-sm-2">
												<button class="btn btn-success " id="btnAnadirDisp"> <i class="fa fa-plus" aria-hidden="true"></i> Añadir</button>
											</div>
										</div>
										<div class="form-group">
											<div class="col-md-12">
												<table id="tabla_marca" class="table table-striped table-bordered">
													<thead>
														<tr>
															<th width="5%">#</th>
															<th hidden></th>
															<th width="30%">Dispositivo</th>
															<th hidden></th>
															<th width="25%">Marca - Modelo</th>
															<th width="25%">Serie</th>
															<th width="8%">Operativo</th>
															<th width="30%">Accion</th>
														</tr>
													</thead>
													<tbody>
													</tbody>
												</table>			
											</div>
											<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
										</div>
									</div>
								</div>
								<div id="step-4" style="display: none" >
									<h2 class="StepTitle"><strong>Software</strong></h2>
									<div class="form-horizontal form-label-left">
										<div class="form-group">
											<label for="" class="col-sm-1 control-label"><b>Software:</b></label>
											<div class="col-sm-3">
												<input class="form-control" name="txtSoftCL" id="txtSoftCL" type="text" placeholder="Buscar" value="" style="text-transform:uppercase">
												<input type="hidden" id="txtIdSofCl">
												<input type="hidden" id="tipoSoft">
											</div>
											<label for="" class="col-sm-1 control-label"><b>Edicion:</b></label>
											<div class="col-sm-2">
												<input class="form-control" name="txtSoftEdicion" id="txtSoftEdicion" type="text" value="" style="text-transform:uppercase">
											</div>
											<label for="" class="col-sm-1 control-label"><b>Version:</b></label>
											<div class="col-sm-1">
												<input class="form-control" name="txtSoftVersion" id="txtSoftVersion" type="text" value="" style="text-transform:uppercase">
											</div>
											<label for="" class="col-sm-1 control-label"><b>F. Install:</b></label>
											<div class="col-sm-1">
												<input type='date' class="form" value='<?= (date("Y") . "-" . date("m") . "-" . date("d")); ?>'>
											</div>

										</div>
										<div class="form-group">
											<label class="col-sm-1 control-label"><b>Licenciado:</b></label>
											<div class="col-sm-1">
												<?=
												$datos != null ? $datos['vigencia'] == true ? '<input type="checkbox" name="chkLicencia" id="chkLicencia" value="1" checked>' :
																'<input type="checkbox" name="chkLicencia" id="chkLicencia" value="1">' : '<input type="checkbox" id="chkLicencia" name="chkLicencia" value="1"><br>';
												?>
											</div>

											<div id="divLicencia" style="display: none" >
												<label for="" class="col-sm-1 control-label"><b>Nº Lic:</b></label>
												<div class="col-sm-4">
													<input class="form-control" name="txtSoftNroLicencia" id="txtSoftNroLicencia" type="text" value="" style="text-transform:uppercase">
												</div>
												<div class="col-sm-1">
												<label id='lblNSerieSoft' style="color:red; display: none" > <img src="../../../../img/uncheck.png" width="20px" height="20px" >Ya Existe!</label>
												<label  id='lblASerieSoft'style='display: none'> <img src="../../../../img/check.png" width="20px" height="20px" ></label>
											</div>

												<label for="" class="col-sm-1 control-label"><b>Vigencia:</b></label>
												<div class="col-sm-1">
													<input class="form-control" name="txtAnioVigente" id="txtAnioVigente" placeholder="años" type="text" value="" style="text-transform:uppercase">
												</div>

											</div>
											<button class="btn btn-success " id="btnAnadirSoft"> <i class="fa fa-plus" aria-hidden="true"></i> Añadir</button>
										</div>

										<div class="form-group">
											<div class="col-md-12">
												<table id="tabla_soft" class="table table-striped table-bordered">
													<thead>
														<tr>
															<th width="3%">#</th>
															<th hidden></th>
															<th width="15%">Tipo Software</th>
															<th hidden></th>
															<th width="12%">Software</th>
															<th width="12%">Edicion</th>
															<th width="4%">Version</th>
															<th width="4%">Licenciado</th>
															<th width="20%">Nº Licencia</th>
															<th width="30%">Accion</th>
														</tr>
													</thead>
													<tbody>
													</tbody>
												</table>
											</div>
											<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
											<center><button class="btn btn-primary " id="btnguardar"> <i class="fa fa-plus" aria-hidden="true"></i> Registrar FICHA</button></center>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>

	<script src="<?php echo $this->basePath() ?>/vendors/jquery/dist/jquery.min.js"></script>
	<script src="<?php echo $this->basePath() ?>/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="<?php echo $this->basePath() ?>/vendors/fastclick/lib/fastclick.js"></script>
	<script src="<?php echo $this->basePath() ?>/vendors/nprogress/nprogress.js"></script>
	<script src="<?php echo $this->basePath() ?>/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
	<script src="<?php echo $this->basePath() ?>/vendors/moment/min/moment.min.js"></script>
	<script src="<?php echo $this->basePath() ?>/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
	<script src="<?php echo $this->basePath() ?>/vendors/jQuery-Smart-Wizard/js/jquery.smartWizard.js"></script>
	<script src="<?php echo $this->basePath() ?>/build/js/custom.min.js"></script>
<?php } ?>

<?=
		$this->inlineScript()
		->prependFile($this->basePath('js/js_ficha.js'))
		->prependFile($this->basePath('js/jquery-ui.js'))
		->prependFile($this->basePath('js/bootbox.js'))
		->prependFile($this->basePath('js/jquery.form.js'))
?>
<script>

	$(document).ready(function () {
		$(".actionBar").hide();
		$("#step-1").hide();
	});
</script>
<script>
	(function ()
	{
		var bar = $('.bar');
		var percent = $('.percent');
		var status = $('#status');

		$('#frmSubir').ajaxForm({
			beforeSend: function () {
				status.empty();
				var percentVal = '0%';
				bar.width(percentVal)
				percent.html(percentVal);
			},
			uploadProgress: function (event, position, total, percentComplete) {
				var percentVal = percentComplete + '%';
				bar.width(percentVal)
				percent.html(percentVal);
				//console.log(percentVal, position, total);
			},
			success: function () {
				var percentVal = '100%';
				bar.width(percentVal)
				percent.html(percentVal);
			},
			complete: function (xhr) {
				status.html(xhr.responseText);
			}
		});
	})();
</script>

