<div class="right_col" role="main">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<a class="btn btn-primary" href="<?php echo $this->basePath() ?>/rol/rol/form/0/1">Nuevo</a>
                    <ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
				</div>
				<div class="x_content">
					<h2>Lista de Rol</h2>
                    <table id="datatable" class="table table-striped table-bordered">
						<thead>
							<tr><th>Nombre</th><th>Descripcion</th><th>Fecha de Registro</th><th>Vigencia</th><th>Acciones</th><th style="display:none">c</th></tr>
						</thead>
						<tbody>
							<?php foreach ($this->roles as $rol) { ?>
								<tr>
									<td><?php echo $rol['nombre'] ?></td>
									<td><?php echo $rol['descripcion'] ?></td>
									<td><?php echo $rol['fecha_registro'] ?></td>
									<td><?= $rol['vigencia'] == 1 ? "<i class='fa fa-check'></i>" : "<i class='fa fa-remove'></i>"; ?></td>
									<td><a class="btn btn-success" title="Editar" href="<?php echo $this->basePath("rol/rol/form/1/" . $rol['id_rol'] . ""); ?>"><img alt="Editar" style="width:20px;" src="../../img/edit.png"></a>
										
										<?= $rol['vigencia'] == 1 ? "<a class='btn btn-danger btnBorrar' title='Eliminar'><img alt='Eliminar' style='width:19px;' src='../../img/delete.png'></a>" : "<input type='button' class='btn btn-success btnActivar'  value='Activar'/>" ?>
									</td>
									<td id="idCod" style="display:none;"><?= $rol['id_rol'] ?></td>
								</tr>
							<?php } ?>
						</tbody>
						<tfoot>
							<tr><th>Nombre</th><th>Descripcion</th><th>Fecha de Registro</th><th>Vigencia</th><th>Acciones</th></tr>
						</tfoot>
                    </table>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->basePath() ?>/vendors/jquery/dist/jquery.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/fastclick/lib/fastclick.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/nprogress/nprogress.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/jszip/dist/jszip.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/pdfmake/build/pdfmake.min.js"></script>
<script src="<?php echo $this->basePath() ?>/build/js/custom.min.js"></script>

<?=
		$this->inlineScript()
		->prependFile($this->basePath('js/js_rol.js'))
?>