<?php if ($mantenimiento != null) { ?>
	<div class="right_col" role="main" style="min-height: 771px;">
		<div class="">
			<div class="clearfix"></div>
			<div class="row">
				<div c="" lass="col-md-12 col-sm-12 col-xs-12">
					<div class="x_panel">
						<div class="x_title">
							<h2><?php echo $this->mantenimiento ?> Marca<small></small></h2>
							<ul class="nav navbar-right panel_toolbox">
								<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
							</ul>
							<div class="clearfix"></div>
						</div>
						<div class="x_content">
							<form class="form-horizontal form-label-left" id="formRegistro"  action="javascript:void(0)"  >
								<br>
								<div class="form-group">
									<label class="col-sm-2 control-label"><b>Marca:</b></label>
									<div class="col-sm-7">
										<input type="hidden" class="" name="txtId" id="txtId"  placeholder=""  value="<?= $datos != null ? $datos['id_marca'] : ''; ?>">
										<input type="text" id="txtDescripcion" name="txtDescripcion" class="form-control descripcion" required=""  autofocus="autofocus" value="<?= $datos != null ? $datos['descripcion'] : ''; ?>">
										<input type="hidden" id="idAnio">
									</div>
									<!--label class="col-sm-2 control-label"><b>Vigencia:</b></label>
								   <div class="col-sm-1">
									<?=
									$datos != null ? $datos['vigencia'] == true ? '<input type="checkbox" name="chkVigencia" value="1" checked>' :
													'<input type="checkbox" name="chkVigencia" value="1">' : '<input type="checkbox" name="chkVigencia" value="1" checked><br>';
									?>
								   </div>
									-->
								</div>
								<br>
								<hr>
								<div class="form-group">
									<center><div class="col-sm-9">
											<button type="submit" id="btnguardar" class="btn btn-primary"><?php echo $this->textBoton ?></button>
										</div></center>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

<?php } ?>
<script src="<?php echo $this->basePath() ?>/vendors/jquery/dist/jquery.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/fastclick/lib/fastclick.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/nprogress/nprogress.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/moment/min/moment.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
<script src="<?php echo $this->basePath() ?>/build/js/custom.min.js"></script>


<?=
		$this->inlineScript()
		->prependFile($this->basePath('js/js_marca.js'))
?>