<!DOCTYPE html>
<html lang="en">
	<head>
		<?php
		echo $this->headMeta()
				->appendName('viewport', 'width=device-width, initial-scale=1.0')
				->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>
		<meta charset="UTF-8">
		<!--<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0,minimal-ui">-->

		<meta name="description" content="SISTEMA DE INVENTARIO - GERESA"> 
		<!--<link rel="shortcut icon" sizes="196x196" href="assets/images/logo.png">-->
		<?php echo $this->headTitle('SISTIN')->setSeparator(' - ')->setAutoEscape(false) ?>


		<link href="<?php echo $this->basePath() ?>/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
		
		<link href="<?php echo $this->basePath() ?>/css/autcomplete_style.css" rel="stylesheet">
		<link href="<?php echo $this->basePath() ?>/css/jquery-ui.css" rel="stylesheet">
		<!-- Font Awesome -->
		<link href="<?php echo $this->basePath() ?>/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
		<!-- NProgress -->
		<link href="<?php echo $this->basePath() ?>/vendors/nprogress/nprogress.css" rel="stylesheet">
		<!-- iCheck -->
		<link href="<?php echo $this->basePath() ?>/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

		<!-- bootstrap-progressbar -->
		<link href="<?php echo $this->basePath() ?>/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
		<!-- JQVMap -->
		<link href="<?php echo $this->basePath() ?>/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
		<!-- bootstrap-daterangepicker -->
		<link href="<?php echo $this->basePath() ?>/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

		<!-- Custom Theme Style -->
		<link href="<?php echo $this->basePath() ?>/build/css/custom.min.css" rel="stylesheet">


		<script src="<?php echo $this->basePath() ?>/libs/bower/breakpoints.js/dist/breakpoints.min.js"></script>

	</head>
	<body class="nav-md">
		<div class="container body">
			<div class="main_container">
				<div class="col-md-3 left_col">
					<div class="left_col scroll-view">
						<div class="navbar nav_title" style="border: 0;">
							<a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>SISTIN - GERESA</span></a>
						</div>
						<div class="clearfix"></div>
						<!-- menu profile quick info -->
						<div class="profile clearfix">
							<div class="profile_pic">
								<img src="images/img.jpg" alt="..." class="img-circle profile_img">
							</div>
							<div class="profile_info">
								<span>Bienvenido,</span>
								<h2>Paul Gonzales</h2>
							</div>
						</div>
						<!-- /menu profile quick info -->

						<br />

						<!-- sidebar menu -->
						<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
							<div class="menu_section">
								<h3>General</h3>
								<ul class="nav side-menu">
									<li><a><i class="fa fa-home"></i> Inicio <span class="fa fa-chevron-down"></span></a>
										<ul class="nav child_menu">
											
											<li><a href="<?php echo $this->basePath()?>/accion/accion/accion">Accion</a></li>

											<li><a href="<?php echo $this->basePath()?>/anio/anio/listadoanios">Anio</a></li>
											<li><a href="<?php echo $this->basePath()?>/marca/marca/marca">Marca</a></li>
											<li><a href="<?php echo $this->basePath()?>/modelo/modelo/modelo">Modelo</a></li>
											<li><a href="<?php echo $this->basePath()?>/dispositivo/dispositivo/dispositivo">Dispositivo</a></li>
											<li><a href="<?php echo $this->basePath()?>/ficha/ficha/ficha">Ficha Tecnica de Equipos de Computo</a></li>
											<li><a href="<?php echo $this->basePath()?>/unidad/unidad/unidad">Unidad</a></li>
										    <li><a href="<?php echo $this->basePath()?>/red/red/red">Red</a></li>
											
											<li><a href="<?php echo $this->basePath()?>/estado/estado/estado">Estado</a></li>
											

											<li><a href="<?php echo $this->basePath()?>/tipoatencion/tipoatencion/tipoatencion">Tipo de Atencion </a></li>

											
										</ul>
									</li>
									<!--li><a><i class="fa fa-edit"></i> Formularios <span class="fa fa-chevron-down"></span></a>
										<ul class="nav child_menu">
											<li><a href="form.html">General Form</a></li>
											<li><a href="form_advanced.html">Advanced Components</a></li>
											<li><a href="form_validation.html">Form Validation</a></li>
											<li><a href="form_wizards.html">Form Wizard</a></li>
											<li><a href="form_upload.html">Form Upload</a></li>
											<li><a href="form_buttons.html">Form Buttons</a></li>
										</ul>
									</li>
									<li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
										<ul class="nav child_menu">
											<li><a href="general_elements.html">General Elements</a></li>
											<li><a href="media_gallery.html">Media Gallery</a></li>
											<li><a href="typography.html">Typography</a></li>
											<li><a href="icons.html">Icons</a></li>
											<li><a href="glyphicons.html">Glyphicons</a></li>
											<li><a href="widgets.html">Widgets</a></li>
											<li><a href="invoice.html">Invoice</a></li>
											<li><a href="inbox.html">Inbox</a></li>
											<li><a href="calendar.html">Calendar</a></li>
										</ul>
									</li>
									<li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
										<ul class="nav child_menu">
											<li><a href="tables.html">Tables</a></li>
											<li><a href="tables_dynamic.html">Table Dynamic</a></li>
										</ul>
									</li>
									<li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
										<ul class="nav child_menu">
											<li><a href="chartjs.html">Chart JS</a></li>
											<li><a href="chartjs2.html">Chart JS2</a></li>
											<li><a href="morisjs.html">Moris JS</a></li>
											<li><a href="echarts.html">ECharts</a></li>
											<li><a href="other_charts.html">Other Charts</a></li>
										</ul>
									</li>
									<li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
										<ul class="nav child_menu">
											<li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
											<li><a href="fixed_footer.html">Fixed Footer</a></li>
										</ul>
									</li-->
								</ul>
							</div>
							<div class="menu_section">
								<!--h3>Live On</h3>
								<ul class="nav side-menu">
									<li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
										<ul class="nav child_menu">
											<li><a href="e_commerce.html">E-commerce</a></li>
											<li><a href="projects.html">Projects</a></li>
											<li><a href="project_detail.html">Project Detail</a></li>
											<li><a href="contacts.html">Contacts</a></li>
											<li><a href="profile.html">Profile</a></li>
										</ul>
									</li>
									<li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
										<ul class="nav child_menu">
											<li><a href="page_403.html">403 Error</a></li>
											<li><a href="page_404.html">404 Error</a></li>
											<li><a href="page_500.html">500 Error</a></li>
											<li><a href="plain_page.html">Plain Page</a></li>
											<li><a href="login.html">Login Page</a></li>
											<li><a href="pricing_tables.html">Pricing Tables</a></li>
										</ul>
									</li>
									<li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
										<ul class="nav child_menu">
											<li><a href="#level1_1">Level One</a>
											<li><a>Level One<span class="fa fa-chevron-down"></span></a>
												<ul class="nav child_menu">
													<li class="sub_menu"><a href="level2.html">Level Two</a>
													</li>
													<li><a href="#level2_1">Level Two</a>
													</li>
													<li><a href="#level2_2">Level Two</a>
													</li>
												</ul>
											</li>
											<li><a href="#level1_2">Level One</a>
											</li>
										</ul>
									</li>                  
									<li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
								</ul-->
							</div>

						</div>
						<!-- /sidebar menu -->

						<!-- /menu footer buttons -->
						<div class="sidebar-footer hidden-small">
							<a data-toggle="tooltip" data-placement="top" title="Settings">
								<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
							</a>
							<a data-toggle="tooltip" data-placement="top" title="FullScreen">
								<span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
							</a>
							<a data-toggle="tooltip" data-placement="top" title="Lock">
								<span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
							</a>
							<a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
								<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
							</a>
						</div>
						<!-- /menu footer buttons -->
					</div>
				</div>

				<!-- top navigation -->
				<div class="top_nav">
					<div class="nav_menu">
						<nav>
							<div class="nav toggle">
								<a id="menu_toggle"><i class="fa fa-bars"></i></a>
							</div>

							<ul class="nav navbar-nav navbar-right">
								<h2><label>GERESA LAMBAYEQUE</label></h2>
							</ul>
							<ul class="nav navbar-nav navbar-right">
								<ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
									<li>
										<a>
											<span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
											<span>
												<span>John Smith</span>
												<span class="time">3 mins ago</span>
											</span>
											<span class="message">
												Film festivals used to be do-or-die moments for movie makers. They were where...
											</span>
										</a>
									</li>
									<li>
										<a>
											<span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
											<span>
												<span>John Smith</span>
												<span class="time">3 mins ago</span>
											</span>
											<span class="message">
												Film festivals used to be do-or-die moments for movie makers. They were where...
											</span>
										</a>
									</li>
									<li>
										<a>
											<span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
											<span>
												<span>John Smith</span>
												<span class="time">3 mins ago</span>
											</span>
											<span class="message">
												Film festivals used to be do-or-die moments for movie makers. They were where...
											</span>
										</a>
									</li>
									<li>
										<a>
											<span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
											<span>
												<span>John Smith</span>
												<span class="time">3 mins ago</span>
											</span>
											<span class="message">
												Film festivals used to be do-or-die moments for movie makers. They were where...
											</span>
										</a>
									</li>
									<li>
										<div class="text-center">
											<a>
												<strong>See All Alerts</strong>
												<i class="fa fa-angle-right"></i>
											</a>
										</div>
									</li>
								</ul>
								</li>
							</ul>
						</nav>
					</div>
				</div>

				<!-- FIN MENUBAR -->
				<main id="app-main" class="app-main">
					<div class="wrap">
						<section class="app-content">
							<?php echo $this->content; ?>
						</section>
					</div>
				</main>

			</div>
		</div>
		
				</body>
				</html>
