<!DOCTYPE html>
<html lang="en">
	<head>
		<?php
		echo $this->headMeta()
				->appendName('viewport', 'width=device-width, initial-scale=1.0')
				->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>
		<meta charset="UTF-8">
		<!--<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0,minimal-ui">-->

		<meta name="description" content="SISTEMA DE INVENTARIO - GERESA"> 
		<!--<link rel="shortcut icon" sizes="196x196" href="assets/images/logo.png">-->
		<?php echo $this->headTitle('SISTIN')->setSeparator(' - ')->setAutoEscape(false) ?>


		<link href="<?php echo $this->basePath() ?>/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
		
		<link href="<?php echo $this->basePath() ?>/css/autcomplete_style.css" rel="stylesheet">
		<link href="<?php echo $this->basePath() ?>/css/jquery-ui.css" rel="stylesheet">
		<!-- Font Awesome -->
		<link href="<?php echo $this->basePath() ?>/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
		<!-- NProgress -->
		<link href="<?php echo $this->basePath() ?>/vendors/nprogress/nprogress.css" rel="stylesheet">
		<!-- iCheck -->
		<link href="<?php echo $this->basePath() ?>/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

		<!-- bootstrap-progressbar -->
		<link href="<?php echo $this->basePath() ?>/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
		<!-- JQVMap -->
		<link href="<?php echo $this->basePath() ?>/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
		<!-- bootstrap-daterangepicker -->
		<link href="<?php echo $this->basePath() ?>/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

		<!-- Custom Theme Style -->
		<link href="<?php echo $this->basePath() ?>/build/css/custom.min.css" rel="stylesheet">


		<script src="<?php echo $this->basePath() ?>/libs/bower/breakpoints.js/dist/breakpoints.min.js"></script>

	</head>
	<body class="nav-md">
		<div class="container body">
			<div class="main_container">
			

				<!-- FIN MENUBAR -->
				<main id="app-main" class="app-main">
					<div class="wrap">
						<section class="app-content">
							<?php echo $this->content; ?>
						</section>
					</div>
				</main>

			</div>
		</div>
		
				</body>
				</html>
				