<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('SISCOMAVE')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('assets/css/style-responsive.css'))   
            ->prependStylesheet($this->basePath('assets/css/style.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()

        ?>
    </head>
    <body class="sticky-header">

        <section>


    <!-- left side start-->
    <div class="left-side sticky-left-side">

        <!--logo and iconic logo start-->
        <div class="logo">
            <a href="index.html"><img src="assets/images/logo.png" alt=""></a>
        </div>

        <div class="logo-icon text-center">
            <a href="index.html"><img src="assets/images/logo_icon.png" alt=""></a>
        </div>
        <!--logo and iconic logo end-->


        <div class="left-side-inner">

  <!--sidebar nav start-->
            <ul class="nav nav-pills nav-stacked custom-nav">
                <li ><a href="index.php"><i class="fa fa-home"></i> <span>Inicio</span></a>
                   
                </li>
                <li class="menu-list"><a href="#"><i class="fa fa-laptop"></i> <span>Mantenimientos y Reparacion</span></a>
                    <ul class="sub-menu-list">
                        <li ><a href="tipomantenimiento.php">Tipo Mantenimiento</a></li>
                        <li><a href="tipodeunidad.php"> Tipo de Unidad</a></li>
                        <li><a href="unidad-maquinaria.php">Maquinaria</a></li>

                    </ul>
                </li>

                 <li class="menu-list"><a href="#"><i class="fa fa-wrench"></i> <span>Servicios de Mantenimientos</span></a>
                    <ul class="sub-menu-list">
                          <li><a href="servicios.php">Servicios</a></li>
                       

                    </ul>
                </li>
                

            </ul>
            <!--sidebar nav end-->

        </div>
    </div>
    <!-- left side end-->
    
    <!-- main content start-->
    <div class="main-content" >

        <!-- header section start-->
        <div class="header-section">

        <!--toggle button start-->
        <a class="toggle-btn"><i class="fa fa-bars"></i></a>
        <!--toggle button end-->

        <!--notification menu start -->
        <div class="menu-right">
            <ul class="notification-menu">                                               
                <li>
                    <a href="blank_page.html#" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <img src="assets/images/photos/user-avatar.png" alt="" />
                        Usuario
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-usermenu pull-right">
                        <li><a href="blank_page.html#"><i class="fa fa-sign-out"></i>Salir</a></li>
                    </ul>
                </li>

            </ul>
        </div>
        <!--notification menu end -->

        </div>
        <!-- header section end-->



            <?= $this->content ?>


        <!--footer section start-->
        <footer class="sticky-footer">
            2016 - Gobierno Regional Lambayeque
        </footer>
        <!--footer section end-->


    </div>
    <!-- main content end-->

            
            
        </section>        

        <?= $this->inlineScript()
            ->prependFile($this->basePath('assets/js/scripts.js'))
            ->prependFile($this->basePath('assets/js/jquery.nicescroll.js'))
            ->prependFile($this->basePath('assets/js/modernizr.min.js'))
            ->prependFile($this->basePath('assets/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assets/js/jquery-migrate-1.2.1.min.js'))
            ->prependFile($this->basePath('assets/js/jquery-ui-1.9.2.custom.min.js'))
            ->prependFile($this->basePath('assets/js/jquery-1.10.2.min.js'))
            
        ?>

    </body>
</html>