<!DOCTYPE html>
<html lang="en">
<head>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
<!--     <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0,minimal-ui">
    <meta name="description" content="Admin, Dashboard, Bootstrap"> -->
    <link rel="shortcut icon" sizes="196x196" href="assets/images/logo.png">
        <?php echo $this->headTitle('SISCOMAVE '. $this->translate('Skeleton Application2'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800,900,300">
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        
                        ->prependStylesheet($this->basePath() . '/assets/css/app.min.css')
                        ->prependStylesheet($this->basePath() . '/libs/bower/material-design-iconic-font/dist/css/material-design-iconic-font.css')
                        ->prependStylesheet($this->basePath() . '/libs/bower/font-awesome/css/font-awesome.min.css') ?>           
<!--     <link rel="stylesheet" href="libs/bower/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="libs/bower/material-design-iconic-font/dist/css/material-design-iconic-font.css">
    <link rel="stylesheet" href="assets/css/app.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800,900,300"> -->
    <script src="<?php echo $this->basePath()?>/libs/bower/breakpoints.js/dist/breakpoints.min.js"></script>
    <script>Breakpoints();</script>
</head>
<body class="menubar-left menubar-unfold menubar-light theme-primary">
<!-- INICIO TOPBAR -->

    <nav id="app-navbar" class="navbar navbar-inverse navbar-fixed-top primary">
        <div class="navbar-header">
            <button type="button" id="menubar-toggle-btn" class="navbar-toggle visible-xs-inline-block navbar-toggle-left hamburger hamburger--collapse js-hamburger">
                <span class="sr-only">Toggle navigation</span>
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
            <button type="button" class="navbar-toggle navbar-toggle-right collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="zmdi zmdi-hc-lg zmdi-more"></span>
            </button>
            <button type="button" class="navbar-toggle navbar-toggle-right collapsed" data-toggle="collapse" data-target="#navbar-search" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="zmdi zmdi-hc-lg zmdi-search"></span>
            </button>
            <a href="index.html" class="navbar-brand">
                <span class="brand-icon"><i class="fa fa-gg"></i></span>
                <span class="brand-name">Infinity</span>
            </a>
        </div>
        <div class="navbar-container container-fluid">
            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <ul class="nav navbar-toolbar navbar-toolbar-left navbar-left">
                    <li class="hidden-float hidden-menubar-top">
                        <a href="javascript:void(0)" role="button" id="menubar-fold-btn" class="hamburger hamburger--arrowalt is-active js-hamburger">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </a>
                    </li>
                    <li>
                        <h5 class="page-title hidden-menubar-top hidden-float"></h5>
                    </li>
                </ul>
                <ul class="nav navbar-toolbar navbar-toolbar-right navbar-right">
<!--                     <li class="nav-item dropdown hidden-float">
                        <a href="javascript:void(0)" data-toggle="collapse" data-target="#navbar-search" aria-expanded="false"><i class="zmdi zmdi-hc-lg zmdi-search"></i></a>
                    </li> -->

                    <li class=" dropdown">
                    
                        <a href="javascript:void(0)" class="dropdown-toggle avatar avatar-md avatar-circle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <!-- <i class="zmdi zmdi-hc-lg zmdi-settings"></i> -->
                            <img class="img-responsive " src="<?php echo $this->basePath() ?>/assets/images/221.jpg" alt="avatar">
                        </a>                        
                    

                    <ul class="dropdown-menu animated flipInY">
                        <li><a href="javascript:void(0)"><i class="zmdi m-r-md zmdi-hc-lg zmdi-account-box"></i>My Profile</a></li>
                        <li><a href="javascript:void(0)"><i class="zmdi m-r-md zmdi-hc-lg zmdi-balance-wallet"></i>Balance</a></li>
                        <li><a href="javascript:void(0)"><i class="zmdi m-r-md zmdi-hc-lg zmdi-phone-msg"></i>Connection<span class="label label-primary">3</span></a></li>
                        <li><a href="javascript:void(0)"><i class="zmdi m-r-md zmdi-hc-lg zmdi-info"></i>privacy</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>


<!-- FIN NAVBAR -->


<!-- INICIO MENUBAR -->
<aside id="menubar" class="menubar light">
<!--     <div class="app-user">
        <div class="media">
            <div class="media-left">
                <div class="avatar avatar-md avatar-circle">
                    <a href="javascript:void(0)">
                        <img class="img-responsive" src="assets/images/221.jpg" alt="avatar"></a>
                    </div>
                </div>
                <div class="media-body">
                    <div class="foldable">
                        <h5><a href="javascript:void(0)" class="username">John Doe</a></h5>
                        <ul>
                            <li class="dropdown">
                                <a href="javascript:void(0)" class="dropdown-toggle usertitle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <small>Web Developer</small>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu animated flipInY">
                                    <li>
                                        <a class="text-color" href="index.html">
                                            <span class="m-r-xs"><i class="fa fa-home"></i></span>
                                            <span>Home</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="text-color" href="profile.html">
                                            <span class="m-r-xs">
                                                <i class="fa fa-user"></i>
                                            </span>
                                            <span>Profile</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="text-color" href="http://envato.rathemes.com/infinity/default/settings.html">
                                            <span class="m-r-xs">
                                                <i class="fa fa-gear"></i>
                                            </span>
                                            <span>Settings</span>
                                        </a>
                                    </li>
                                    <li role="separator" class="divider"></li>
                                    <li><a class="text-color" href="http://envato.rathemes.com/infinity/default/logout.html"><span class="m-r-xs"><i class="fa fa-power-off"></i></span><span>Home</span></a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> -->
        <div class="menubar-scroll">
            <div class="menubar-scroll-inner">
                <ul class="app-menu">
                    <li class="has-submenu">
                        <a href="javascript:void(0)" class="submenu-toggle">
                            <i class="menu-icon zmdi zmdi-view-dashboard zmdi-hc-lg"></i>
                            <span class="menu-text">Dashboards</span>
                            <i class="menu-caret zmdi zmdi-hc-sm zmdi-chevron-right"></i>
                        </a>
                        <ul class="submenu">
                            <li>
                                <a href="index.html">
                                    <span class="menu-text">Dashboard 1</span>
                                </a>
                            </li>
                            <li>
                                <a href="dashboard.2.html">
                                    <span class="menu-text">Dashboard 2</span>
                                </a>
                            </li>
                            <li>
                                <a href="dashboard.3.html">
                                    <span class="menu-text">Dashboard 3</span>
                                </a>
                            </li>
                        </ul>
                    </li>                    
                </ul>
            </div>
        </div>
    </aside>

<!-- FIN MENUBAR -->

<!--     <div id="navbar-search" class="navbar-search collapse">
        <div class="navbar-search-inner">
            <form action="index.html#">
                <span class="search-icon">
                    <i class="fa fa-search"></i>
                </span>
                <input class="search-field" type="search" placeholder="search...">
            </form>
            <button type="button" class="search-close" data-toggle="collapse" data-target="#navbar-search" aria-expanded="false">
                <i class="fa fa-close"></i>
            </button>
        </div>
        <div class="navbar-search-backdrop" data-toggle="collapse" data-target="#navbar-search" aria-expanded="false"></div>
    </div> -->


<main id="app-main" class="app-main">
    <div class="wrap">
        <section class="app-content">

<?php echo $this->content; ?>


            </section>
        </div>

</main>




<!-- <script src="assets/js/core.min.js"></script>
<script src="assets/js/app.min.js"></script>
<script src="libs/bower/moment/moment.js"></script>
<script src="libs/bower/fullcalendar/dist/fullcalendar.min.js"></script>
<script src="assets/js/fullcalendar.js"></script> -->
</body>
</html>
