<?php
//echo $_SERVER['SCRIPT_NAME'];
include_once("config/autoload/conexion.php");
$obcon= new Conexion("172.16.0.152","user_geresa","user_geresa2017","siganew",5432);
$consulta = "select * from remoto.view_unidades";
$ejecquery = pg_query($obcon->getConexion(), $consulta);
?>
<div class="right_col" role="main">
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<a class="btn btn-primary" href="<?php echo $this->basePath() ?>/unidad/unidad/form/0/1">Nuevo</a>
                    <ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
				</div>
				<div class="x_content">
					<h2>Lista de Unidades Organicas</h2>
                    <table id="datatable" class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>Descripción</th>
								<th>Nombre Corto</th>
								<th>Jefe</th>
								<th>Vigencia</th>
								<th>Accciones</th>
								<th style="display:none">c</th>
							</tr>
						</thead>
						<tbody>

							<?php while ($reg = pg_fetch_assoc($ejecquery)){?>
  <tr>
    <td><?=utf8_encode($reg['depe_nombre'])?></td>
    <td><?=utf8_encode($reg['depe_nombrecorto'])?></td>
	<td><?=utf8_encode($reg['jefe'])?></td>
	<td><i class='fa fa-check'></i></td>
	<td><a class='btn btn-success' 
			   href='
			<?= $this->basePath('unidad/unidad/form/1/'. $reg['depe_id'].'')?>'>
			<img alt='Ver' style='width:20px;' src='../../img/ver.png'></a></td>	
			   <td id="idCod" style="display:none;"></td>
   </tr>
 <?php }?>
							<!--<?php foreach ($this->unidades as $unidad) { ?>
								<tr>
									<td><?php echo $unidad['descripcion'] ?></td>
									<td><?= $unidad['vigencia'] == 1 ? "<i class='fa fa-check'></i>" : "<i class='fa fa-remove'></i>"; ?></td>
									<td><?= $unidad['vigencia'] == 1 ? "<i class='fa fa-check'></i>" : "<i class='fa fa-remove'></i>"; ?></td>
									<td><?= $unidad['vigencia'] == 1 ? "<i class='fa fa-check'></i>" : "<i class='fa fa-remove'></i>"; ?></td>
									<td>
										<a class="btn btn-default"href="<?php echo $this->basePath("unidad/unidad/form/1/" . $unidad['id_uni_org'] . ""); ?>">Editar</a>
										<?= $unidad['vigencia'] == 1 ? "<input type='button' class='btn btn-danger btnBorrar'  value='Desactivar'/>" : "<input type='button' class='btn btn-success btnActivar'  value='Activar'/>" ?>
									 </td>
									<td id="idCod" style="display:none;"><?= $unidad['id_uni_org'] ?></td>
								</tr>
							<?php } ?>
							-->
						</tbody>
						<tfoot>
							<tr>
								<th>Descripción</th>
								<th>Nombre Corto</th>
								<th>Jefe</th>
								<th>Vigencia</th>
								<th>Acciones</th>
							</tr>
						</tfoot>
                    </table>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->basePath() ?>/vendors/jquery/dist/jquery.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/fastclick/lib/fastclick.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/nprogress/nprogress.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/jszip/dist/jszip.min.js"></script>
<script src="<?php echo $this->basePath() ?>/build/js/custom.min.js"></script>

</script>

<?=
		$this->inlineScript()
		
		->prependFile($this->basePath('js/js_unidad.js'))
?>