<?php if ($mantenimiento != null) { ?>
	<div class="right_col" role="main" style="min-height: 771px;">
		<div class="">
			<div class="clearfix"></div>
			<div class="row">
				<div c="" lass="col-md-12 col-sm-12 col-xs-12">
					<div class="x_panel">
						<div class="x_title">
							<h2><?php echo $this->mantenimiento ?> Dispositivo<small></small></h2>
							<ul class="nav navbar-right panel_toolbox">
								<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
							</ul>
							<div class="clearfix"></div>
						</div>
						<div class="x_content">
							<br>
							<form class="form-horizontal form-label-left" id="formRegistro"  action="javascript:void(0)"  >
								<div class="form-horizontal">
									<div class="form-group">
										<label class="col-sm-2 control-label"><b>Tipo:</b></label>
										<div class="col-sm-4">
											<select id="cmbTipo" name="cmbTipo" class="form-control tipo" required="">
												<option value="SO"
												<?php echo ($datos!=null) ? ($datos['tipo'] =='SO' ? "selected" : "") :"" ?>
														>Sistema Operativo</option>
												<option value="DI" <?php echo ($datos!=null) ? ($datos['tipo'] =='DI' ? "selected" : "") :"" ?>
														>Dispositivos</option>
												<option value="SC" <?php echo ($datos!=null) ? ($datos['tipo'] =='SC' ? "selected" : "") :"" ?>
														>Software Comercial</option>
												<option value="SM" <?php echo ($datos!=null) ? ($datos['tipo'] =='SM' ? "selected" : "") :"" ?>
														>Software Medida</option>
												<option value="SL" <?php echo ($datos!=null) ? ($datos['tipo'] =='SL' ? "selected" : "") :"" ?>
														>Software Libre</option>
											</select>							
										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 control-label"><b>Nombre</b></label>
										<div class="col-sm-10">
											<input class="form-control dispositivo" autofocus="autofocus" name="txtDispositivo" id="txtDispositivo" style="text-transform:uppercase" type="text" value="<?=$datos['descripcion']?>">
											<input class="form-control" name="txtIdDis" id="txtIdDis" value="<?=$datos['id_disp_soft']?>" type="hidden"  >										
											<input class="form-control" name="txtId" id="txtId" value="" type="hidden">
										</div>
									</div>
									<!--<div class="form-group">
										<label class="col-sm-2 control-label"><b>En Ficha Tecnica:</b></label>
										<div class="col-sm-2">
											<div class="radio radio-inline radio-primary">-->
												<input type="hidden" name="rbtFicha" id="rbtFicha" value="si">
												<!--<label>SI</label>
											</div>
											<div class="radio radio-inline radio-primary">
												<input type="radio" name="rbtFicha" id="rbtFicha" value="no"  >
												<label >NO</label>
											</div>
										</div>
									</div>-->
									<br>
									<hr>
									<div class="form-group" id="marca_modelo" style="<?php echo ($datos!=null) ? ($datos['tipo'] !='DI' ? "display:none" : "display:block") :"display:none"?>">
										<div class="col-md-6">
											<label for="" class="col-sm-2 control-label"><b>Marca:</b></label>
											<div class="col-sm-8">
												<input class="form-control " name="bMarca" id="bMarca" placeholder="Buscar..." style="text-transform: uppercase" type="text">
												<input type="hidden" id="id_marca">	
											</div>
											<div class="col-sm-2">
												<!--button class="btn btn-success " id="btnMarca"> <i class="fa fa-plus" aria-hidden="true"></i> Añadir</button-->
											</div>
										</div>
										<div class="col-md-6">
											<label for="" class="col-sm-2 control-label"><b>Modelo:</b></label>
											<div class="col-sm-8">
												<input class="form-control" name="bModelo" id="bModelo" placeholder="Buscar..." style="text-transform: uppercase" type="text">
											</div>
											<div class="col-sm-1">
												<input type="hidden" id="id_modelo">
											</div>
											<div class="col-sm-2">
												<button class="btn btn-success " id="btnMarca"> <i class="fa fa-plus"  aria-hidden="true"></i> Añadir</button>
												<!--button class="btn btn-success " id="btnModelo"> <i class="fa fa-plus" aria-hidden="true"></i> Añadir</button-->
											</div>
										</div>
									</div>
								
									<div class="form-group">
										<div class="col-md-12">
											<table id="tabla_marca" class="table table-striped table-bordered" style="<?php echo ($datos!=null) ? ($datos['tipo'] !='DI' ? "display:none" : "display:block") :"display:none" ?>">
												<thead>
													<tr>
														<th width="5%">#</th>
														<th hidden></th>
														<th width="51%">Marca</th>
														<th hidden></th>
														<th width="90%">Modelo</th>
														<th width="30%">Accion</th>
													</tr>
												</thead>
												<tbody>
													<?php if($datos!=null){
													foreach ($datosDetalle as $dDetalle) { 
											echo "<tr data-id=" .$dDetalle['id_disp_mar_mod'] .">"
												. "<td>#</td>"
												. "<td hidden>" .$dDetalle['id_marca'] . "</td>" 
												. "<td>".$dDetalle['marca']."</td>"
												. "<td hidden>".$dDetalle['id_modelo']."</td>"
												. "<td>".$dDetalle['modelo']."</td>"
												. "<td><button type='button' class='btn btn-danger btn-xs removerM'><i class='fa fa-fw fa-close'></i></button></td>"
											."</tr>";
																	}	
													}?>
												</tbody>
											</table>			
										</div>
									</div>
									<hr id="hrT" style="<?php echo ($datos!=null) ? ($datos['tipo'] !='DI' ? "display:none" : "display:block") :"display:none" ?>" >
									<div class="form-group">
										<div class="form-group">
											<center><div class="col-sm-9">
													<button type="submit" id="btnguardar" class="btn btn-primary"><?php echo $this->textBoton ?></button>
												</div></center>
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php } ?>
<script src="<?php echo $this->basePath() ?>/vendors/jquery/dist/jquery.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/fastclick/lib/fastclick.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/nprogress/nprogress.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/moment/min/moment.min.js"></script>
<script src="<?php echo $this->basePath() ?>/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
<script src="<?php echo $this->basePath() ?>/build/js/custom.min.js"></script>

<?=
		$this->inlineScript()
		->prependFile($this->basePath('js/js_dispositivo.js'))
		->prependFile($this->basePath('js/js_buscar.js'))
		
		->prependFile($this->basePath() . '/assets/js/core.min.js')
?>